### ISSUE TITLE
Add class selector

### ISSUE THREAD

**Issue by sarmong** [manzinello/mailgo#36]
Add the possibility to apply mailgo not to every `mailto:` link, but only to the ones that have a certain class (e.g. `class='mailgo'`)

**Comment by manzinello** [comment]
Interesting! The goal of the script is to transform all the mailto in `mailgo` and with `class="no-mailgo"` you can always specify if you don't want to enable mailgo for a particular link, but I haven't think in the opposite behaviour... I don't think if it can be useful for some particular page with a lot of mailto links, because in the other cases you can specify the normal mailto with `no-mailgo` class https://mailgo.js.org/docs/usage#exclude-a-single-mailto

**Comment by metahnetoutage** [comment]
Manzinello is right, purely with css such specification can be addressed. This is not an enhancement.
