### ISSUE TITLE
Multilingual dist files

### ISSUE THREAD

**Issue by granik** [manzinello/mailgo#82]
We created a [drupal module](https://www.drupal.org/project/mailgo).
Thanks for improving the functionality with nocss-mode.

There is another problem. I cannot change module language, which depends on user's website language. Is it possible to add a file for each language to dist folder? I mean smth like "mailgo.en.min.js, mailgo.en.nocss.min.js, ..." etc. It would be perfect.

I could build these files by myself, but the task is to use always the latest version of mailgo.

Maybe there is another solution? For example, to allow developer confugure the module without its rebuilding?

**Comment by manzinello** [comment]
Everything you are saying can be done very easily through **Mailgo Configuration**! https://mailgo.dev/docs/configuration

`MailgoConfig` is something present in mailgo since a lot of time ago and `lang` was one of the very first attribute you can set, I think that was added several months ago.

Sorry, but the solution of several files in `dist` folder isn't practicable. At the moment **mailgo** has 13 languages in `i18n`. Considering all the combinations it means that the `dist` folder will contain 150+ files.
I think that at the moment it's not a good idea because you can set the language directly through configuration.

Obviously if you need a particular file that you can import without configuration you can just clone the repository and build it yourself without any problem.
